Hangman/ViewModels/GameViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hangman.Models
{
    public class GameViewModel
    {
        public bool IsAuthenticated { get; set; }
        public string UserName { get; set; }
        public string ErrorMessage { get; set; }
    }
}

Hangman/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hangman.Models;
using System.Net.Mail;
using Hangman.Entities;
using Hangman.Services;
using System.Data.Entity;

namespace Hangman.Controllers
{
    public class GameController : Controller
    {
        private static Random _random = new Random();
        private readonly IEntityRepository<Challenge> _challengesRepo;
        private readonly IAuthenticationService _authService;
        private readonly IUserService _userService;
        private readonly IEmailService _emailService;

        public GameController(
            IAuthenticationService authService,
            IUserService userService, 
            IEntityRepository<Challenge> challengesRepo, 
            IEmailService emailService)
        {
            this._userService = userService;
            this._challengesRepo = challengesRepo;
            this._authService = authService;
            this._emailService = emailService;
        }

        public ActionResult Index()
        {
            var model = new GameViewModel();
            model.IsAuthenticated = _authService.IsAuthenticated();
            if (_authService.IsAuthenticated())
            {
                model.UserName = _authService.GetUserName();
            }
            
            return View(model);
        }

        [HttpPost]
        public ActionResult Authenticate(string username, string password)
        {
            if (_userService.Validate(username, password))
            {
                _authService.SetAuthCookie(username, true);
                return RedirectToRoute("Default", new { action = "Index" });
            }
            else
            {
                var model = new GameViewModel() { ErrorMessage = "Wrong user or password." };
                return View("Index", model);
            }
        }

        [HttpGet]
        public ActionResult Logout()
        {
            _authService.Logout();
            return RedirectToRoute("Default", new { action = "Index" });
        }

        [HttpGet]
        public ActionResult Word()
        {
            var challenges = _challengesRepo.GetAll();
            var chosenChallengeIndex = _random.Next(challenges.Count());
            return Json(new {word = challenges.OrderBy(w => w.Id).Skip(chosenChallengeIndex).First().Word}, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Challenges(int startIndex = 0, int maxResults = 100)
        {
            var username = _authService.GetUserName();
            var models = new List<ChallengeViewModel>();

            var challenges = _challengesRepo.GetAll()
                                            .Include(c => c.Results)
                                            .OrderBy(c => c.Id).Skip(startIndex).Take(maxResults).ToArray();
            foreach (var challenge in challenges)
            {
                var challengeViewModel = new ChallengeViewModel(challenge);
                if (username.Equals(challenge.Username, StringComparison.OrdinalIgnoreCase))
                {
                    challengeViewModel.answered = challengeViewModel.correct = true;
                    challengeViewModel.isCreator = true;
                }
                else
                {
                    var result = challenge.Results.FirstOrDefault(c => c.Username.Equals(username, StringComparison.OrdinalIgnoreCase));
                    if (result != null)
                    {
                        challengeViewModel.answered = true;
                        challengeViewModel.correct = result.Correct;
                    }
                }
                
                models.Add(challengeViewModel);
            }

            return Json(models, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Challenges(ChallengeViewModel challengeViewModel)
        {
            var challenge = new Challenge()
            {
                Username = _authService.GetUserName(),
                Word = challengeViewModel.word.ToLowerInvariant()
            };

            _challengesRepo.InsertOnCommit(challenge);
            _challengesRepo.CommitChanges();

            challengeViewModel.id = challenge.Id;
            challengeViewModel.username = challenge.Username;

            _emailService.Send(EmailFactory.CreateNewChallengeMessage(challenge, _userService.GetAllUserEmailAddress()));

            return Json(challengeViewModel);
        }

        [HttpGet]
        public ActionResult ChallengeResults(int challengeId)
        {
            var results = from r in _challengesRepo.GetAll().Where(c => c.Id == challengeId).First().Results
                          select new ChallengeResultViewModel(r);

            return Json(results.ToArray(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize]
        public ActionResult ChallengeResults(ChallengeResultViewModel resultViewModel)
        {
            var user = _authService.GetUserName();
            
            var challenge = _challengesRepo.GetAll().FirstOrDefault(c => c.Id == resultViewModel.challengeId);
            if (challenge == null)
            {
                throw new InvalidOperationException("Challenge was not found.");                
            }
            else if (user.Equals(challenge.Username, StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidOperationException("User was the creator of this challenge.");                
            }

            var result = challenge.Results.FirstOrDefault(r => r.Username.Equals(user, StringComparison.OrdinalIgnoreCase));

            if (result != null)
            {
                throw new InvalidOperationException("User already solved this challenge.");
            }

            var challengeResult = new ChallengeResult()
            {
                Username = user,
                Correct = resultViewModel.correct,
                Challenge = challenge
            };

            challenge.Results.Add(challengeResult);
            _challengesRepo.CommitChanges();

            resultViewModel.id = challengeResult.Id;
            resultViewModel.username = user;

            return Json(resultViewModel);
        }
    }
}

Hangman/Views/Game/Index.cshtml

@model Hangman.Models.GameViewModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>Hangman</title>
    <meta charset="utf-8">
    <meta name="author" content="Federico Silva Armas <fsilva.armas@gmail.com>">
    
    <link href="@Url.Content("~/Content/css/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/App.css")" rel="stylesheet" type="text/css" />
    
    <script src="http://ajax.aspnetcdn.com/ajax/modernizr/modernizr-1.7-development-only.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.1.min.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/js/lib/underscore-min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/js/lib/backbone.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/js/lib/bootstrap-modal.js")" type="text/javascript"></script>

    <script type="text/javascript">var Hangman = {};</script>
    <script src="@Url.Content("~/Content/js/Server.js")" type="text/javascript"></script>
     <script type="text/javascript">
         Hangman.Server.getContextPath = function () { return '@Url.Content("~/")'; }
         Hangman.Server.getCurrentUser = function () { return '@Model.UserName'; }
    </script>

    <script src="@Url.Content("~/Content/js/Models.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/js/Collections.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/js/Views.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/js/Routers.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/js/Startup.js")" type="text/javascript"></script>

    <script type="text/template" id="challenge-template">
        #<%= id %> by <strong><%= username %></strong>
    </script>

    <script type="text/template" id="challenge-list-template">
            <h3>Challenges</h3>
            <div class="sidebarButtons">
                @if (Model.IsAuthenticated)
                {
                    <button class="btn challengeButton" data-toggle="modal" href="#newWordModal">New Challenge</button>
                }
               <button class="btn challengeButton" id="playRandom">Play Random</button>
            </div>
            <div>
                <div class="spinner" />
                <ul class="challenges status-list">
                </ul>
            </div>
            <div id="newWordModal" class="modal fade">
                <form id="newWordForm">
                    <div class="modal-header">
                        <a href="#" class="close" data-dismiss="modal">x</a>
                        <h3>New Challenge</h3>
                    </div>
                    <div class="modal-body">
                        <p>
                            <label for="newWordInput">Word:  </label><input type="text" name="newWordInput" id="newWordInput"></input>
                        </p>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" id="newWordButton" class="btn primary" value="Create" />
                    </div>
                </form>
            </div>
    </script>

    <script type="text/template" id="game-template">
            <div class="hangman">
                <img src='@Url.Content("~/Content/images/hang")/<%= image %>' />
            </div>
            <div class="game-message">
            </div>
            <div id="letters" <% if(captureKeys){ %>class="capture" <%} %>>
                    <% _.each(letters, function(l){ %>
                        <div class="letter">
                        <% if(l.get('isVisible')){ %>
                            <div><%= l.get('value') %></div>
                        <% } %>
                        </div>
                    <% }); %>
            </div>
            <div class="game-results">
                <div id="results" />
            </div>
        <div class="clear" />
        <span class="usedLetters">Used:&nbsp;&nbsp;
            <% if(usedLetters.length == 0) {%> 
                none
            <%}%>
            <% _.each(usedLetters, function(l){ %>
                <%= l %> &nbsp;&nbsp;&nbsp;
            <%});%>
        </span>

        <div class="keyboard">
            <h3>Use your keyboard or click below to guess a letter</h3>
            <% _.each(keyboard, function(l){ %>
                <div class="key <% if(!l.get('isVisible')) {%>hidden<%}%>">
                    <div><%= l.get('value') %></div>
                </div>
            <% }); %>
        </div>
    </script>
</head>
<body>
     <div class="navbar">
        <div class="navbar-inner">
            <div class="container-fluid">
                <a class="brand">Hangman</a>
                    <div class="pull-right navbar-text">
                        @if (!Model.IsAuthenticated)
                        {
                            using (Html.BeginForm("Authenticate", "Game", FormMethod.Post, new { @class = "loginForm" }))
                            { 
                            <text>
                                User: <input type="text" id="username" name="username" value="" />
                                Password: <input type="password" id="password" name="password" value="" />
                                <input type="submit" value="Login" />
                                @if (ViewData["loginError"] != null)
                                {
                                    <br />
                                    <span>Error</span>
                                }
                            </text>
                            }
                        }
                        else
                        {
                            <text>Player: @Model.UserName  [@Html.ActionLink("Logout", "Logout")]</text>
                        }
                    </div>
            </div>
        </div>        
    </div>
    
    @if (!String.IsNullOrEmpty(Model.ErrorMessage))
    { 
        <div class="errorMessage alert alert-block alert-error">@Model.ErrorMessage</div>
    }

    <div class="container-fluid">
        <div class="row-fluid">
            <div class="sidebar span2">
            </div>
            <div class="content span10">
            </div>    
        </div>
    </div>
</body>
</html>